server:
  port: 8081

  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      password: postgres
      username: postgress
      url: jdbc:postgresql://localhost:5433/account-service

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresSQLDialect
        show-sql: true